title: Habezai's Personal Website
description: A Personal Website for Habezai!
theme: just-the-docs

url: https://habezai.github.io

aux_links:
  "本项目源码":
    - "https://github.com/habezai/habezai.github.io"  
  "在线演示":
    - "https://github.com/habezai"  
  "个人GitHub":
    - "https://github.com/habezai"  

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"


exclude: # 构建过程中排除的文件或目录
  - Gemfile
  - Gemfile.lock
  - node_modules/
  # specific to the theme website:
  - bin/
  - lib/
  - "*.gemspec"
  - "*.gem"
  - README.md

# 开启或者禁用搜索功能
search_enabled: true
search:
  # 切分页面为可搜索的独立区块
  # Supports 1 - 6, default: 2
  heading_level: 2
  # 每个搜索结果的最大预览数量
  # Default: 3
  previews: 2
  # 预览中显示的匹配单词之前的最大单词数
  # Default: 5
  preview_words_before: 3
  # 预览中显示的匹配单词之后的最大单词数
  # Default: 10
  preview_words_after: 3
  # 设置搜索令牌分隔符
  # Default: /[\s\-/]+/
  # Example: enable support for hyphenated search words
  # 修改分词器，支持中文标点
  tokenizer_separator: /[\s\/、，。；：！？《》【】（）]+/
  # 在搜索结果中显示相对URL
  # Supports true (default) or false
  rel_url: true
  # 在每个页面的右下角显示搜索按钮
  # Supports true or false (default)
  button: false
  # 按下`ctrl + focus_shortcut_key`（`cmd + focus_shortcut_key`在macOS上）聚焦搜索输入框
  # Default: "k"
  focus_shortcut_key: "k"

enable_copy_code_button: true #在代码块右上角显示“复制”按钮，极大提升用户体验。建议保持开启。

# 是否全局启用侧边栏菜单
# 在页面变量或最小布局中也可以选择性启用或禁用导航菜单
nav_enabled: true

# 导航链接的排序顺序
# nav_sort: case_insensitive # default, equivalent to nil
nav_sort: case_sensitive # Capital letters sorted before lowercase

---
title: Typography
parent: UI Components
nav_order: 1
---

---
title: UI Components
nav_order: 3
---