title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  "GitHub源码":
    - "https://github.com/habezai/habezai.github.io"  
    - "fab fa-github"  
  "在线演示":
    - "https://demo.example.com"
    - "fas fa-rocket"
